// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Empty
	Point
	WriteRequest
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Point struct {
	Lat int32 `protobuf:"varint,1,opt,name=lat" json:"lat,omitempty"`
	Lng int32 `protobuf:"varint,2,opt,name=lng" json:"lng,omitempty"`
	Elv int32 `protobuf:"varint,3,opt,name=elv" json:"elv,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Point) GetLat() int32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLng() int32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *Point) GetElv() int32 {
	if m != nil {
		return m.Elv
	}
	return 0
}

type WriteRequest struct {
	P    *Point `protobuf:"bytes,1,opt,name=p" json:"p,omitempty"`
	Blob string `protobuf:"bytes,2,opt,name=blob" json:"blob,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WriteRequest) GetP() *Point {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *WriteRequest) GetBlob() string {
	if m != nil {
		return m.Blob
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*Point)(nil), "api.Point")
	proto.RegisterType((*WriteRequest)(nil), "api.WriteRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*Empty, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/api.API/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	Write(context.Context, *WriteRequest) (*Empty, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _API_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x62, 0xe7, 0x62, 0x75, 0xcd,
	0x2d, 0x28, 0xa9, 0x54, 0xb2, 0xe5, 0x62, 0x0d, 0xc8, 0xcf, 0xcc, 0x2b, 0x11, 0x12, 0xe0, 0x62,
	0xce, 0x49, 0x2c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0x31, 0xc1, 0x22, 0x79, 0xe9,
	0x12, 0x4c, 0x50, 0x91, 0xbc, 0x74, 0x90, 0x48, 0x6a, 0x4e, 0x99, 0x04, 0x33, 0x44, 0x24, 0x35,
	0xa7, 0x4c, 0xc9, 0x86, 0x8b, 0x27, 0xbc, 0x28, 0xb3, 0x24, 0x35, 0x28, 0xb5, 0xb0, 0x34, 0xb5,
	0xb8, 0x44, 0x48, 0x82, 0x8b, 0xb1, 0x00, 0x6c, 0x06, 0xb7, 0x11, 0x97, 0x1e, 0xc8, 0x4e, 0xb0,
	0xe1, 0x41, 0x8c, 0x05, 0x42, 0x42, 0x5c, 0x2c, 0x49, 0x39, 0xf9, 0x49, 0x60, 0xe3, 0x38, 0x83,
	0xc0, 0x6c, 0x23, 0x7d, 0x2e, 0x66, 0xc7, 0x00, 0x4f, 0x21, 0x0d, 0x2e, 0x56, 0xb0, 0x21, 0x42,
	0x82, 0x60, 0x2d, 0xc8, 0x06, 0x4a, 0x41, 0x4c, 0x81, 0xb8, 0x95, 0x21, 0x89, 0x0d, 0xec, 0x05,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x28, 0x87, 0xda, 0xcf, 0x00, 0x00, 0x00,
}
